package EventLogService;


/**
* EventLogService/_EventLogsImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSTBAA.idl
* 21 August 2020 20:34:18 o'clock IST
*/

public abstract class _EventLogsImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements EventLogService.EventLogs, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _EventLogsImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getStatus", new java.lang.Integer (0));
    _methods.put ("search", new java.lang.Integer (1));
    _methods.put ("alert", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EventLogService/EventLogs/getStatus
       {
         String $result = null;
         $result = this.getStatus ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // EventLogService/EventLogs/search
       {
         String $result = null;
         $result = this.search ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // EventLogService/EventLogs/alert
       {
         String $result = null;
         $result = this.alert ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EventLogService/EventLogs:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _EventLogsImplBase
