package EventLogService;


/**
* EventLogService/EventLogs.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSTBAA.idl
* 21 August 2020 20:34:18 o'clock IST
*/

public interface EventLogs extends EventLogsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventLogs
