package EventLogService;


/**
* EventLogService/EventLogsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSTBAA.idl
* 21 August 2020 20:34:18 o'clock IST
*/

public interface EventLogsOperations 
{
  String getStatus ();
  String search ();
  String alert ();
} // interface EventLogsOperations
