// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemlogs.proto

package services.systemlogs;

public interface CreateReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:systemlogs.CreateReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .systemlogs.StringRequest multirequest = 1;</code>
   */
  java.util.List<services.systemlogs.StringRequest> 
      getMultirequestList();
  /**
   * <code>repeated .systemlogs.StringRequest multirequest = 1;</code>
   */
  services.systemlogs.StringRequest getMultirequest(int index);
  /**
   * <code>repeated .systemlogs.StringRequest multirequest = 1;</code>
   */
  int getMultirequestCount();
  /**
   * <code>repeated .systemlogs.StringRequest multirequest = 1;</code>
   */
  java.util.List<? extends services.systemlogs.StringRequestOrBuilder> 
      getMultirequestOrBuilderList();
  /**
   * <code>repeated .systemlogs.StringRequest multirequest = 1;</code>
   */
  services.systemlogs.StringRequestOrBuilder getMultirequestOrBuilder(
      int index);
}
