// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemlogs.proto

package services.systemlogs;

public interface SpreadSheetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:systemlogs.SpreadSheetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
