// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemlogs.proto

package services.systemlogs;

public interface StoreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:systemlogs.StoreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();

  /**
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 3;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 3;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
