// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemlogs.proto

package services.systemlogs;

public final class SystemLogsServiceImpl {
  private SystemLogsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_systemlogs_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_systemlogs_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_systemlogs_StoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_systemlogs_StoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_systemlogs_CreateReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_systemlogs_CreateReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_systemlogs_SpreadSheetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_systemlogs_SpreadSheetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_systemlogs_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_systemlogs_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_systemlogs_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_systemlogs_StringRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020systemlogs.proto\022\nsystemlogs\" \n\rStatus" +
      "Request\022\017\n\007request\030\001 \001(\t\";\n\014StoreRequest" +
      "\022\017\n\007request\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\r\n\005value\030" +
      "\003 \001(\t\"F\n\023CreateReportRequest\022/\n\014multireq" +
      "uest\030\001 \003(\0132\031.systemlogs.StringRequest\"%\n" +
      "\022SpreadSheetRequest\022\017\n\007request\030\001 \001(\t\"\"\n\016" +
      "StringResponse\022\020\n\010response\030\001 \001(\t\" \n\rStri" +
      "ngRequest\022\017\n\007request\030\001 \001(\t2\277\002\n\021SystemLog" +
      "sService\022D\n\tgetStatus\022\031.systemlogs.Statu" +
      "sRequest\032\032.systemlogs.StringResponse\"\000\022?" +
      "\n\005store\022\030.systemlogs.StoreRequest\032\032.syst" +
      "emlogs.StringResponse\"\000\022M\n\014createReport\022" +
      "\037.systemlogs.CreateReportRequest\032\032.syste" +
      "mlogs.StringResponse\"\000\022T\n\024createLogSprea" +
      "dSheet\022\036.systemlogs.SpreadSheetRequest\032\032" +
      ".systemlogs.StringResponse\"\000B.\n\023services" +
      ".systemlogsB\025SystemLogsServiceImplP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_systemlogs_StatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_systemlogs_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_systemlogs_StatusRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_systemlogs_StoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_systemlogs_StoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_systemlogs_StoreRequest_descriptor,
        new java.lang.String[] { "Request", "Key", "Value", });
    internal_static_systemlogs_CreateReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_systemlogs_CreateReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_systemlogs_CreateReportRequest_descriptor,
        new java.lang.String[] { "Multirequest", });
    internal_static_systemlogs_SpreadSheetRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_systemlogs_SpreadSheetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_systemlogs_SpreadSheetRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_systemlogs_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_systemlogs_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_systemlogs_StringResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_systemlogs_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_systemlogs_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_systemlogs_StringRequest_descriptor,
        new java.lang.String[] { "Request", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
