// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventlogs.proto

package services.eventlogs;

public interface AlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventlogs.AlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
