// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventlogs.proto

package services.eventlogs;

public final class EventlogsServiceImpl {
  private EventlogsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventlogs_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventlogs_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventlogs_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventlogs_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventlogs_AlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventlogs_AlertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventlogs_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventlogs_StringResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017eventlogs.proto\022\teventlogs\" \n\rStatusRe" +
      "quest\022\017\n\007request\030\001 \001(\t\"3\n\rSearchRequest\022" +
      "\017\n\007request\030\001 \001(\t\022\021\n\tparameter\030\002 \001(\t\"?\n\014A" +
      "lertRequest\022\017\n\007request\030\001 \001(\t\022\r\n\005email\030\002 " +
      "\001(\t\022\017\n\007message\030\003 \001(\t\"\"\n\016StringResponse\022\020" +
      "\n\010response\030\001 \001(\t2\326\001\n\020EventLogsService\022B\n" +
      "\tgetStatus\022\030.eventlogs.StatusRequest\032\031.e" +
      "ventlogs.StringResponse\"\000\022?\n\006search\022\030.ev" +
      "entlogs.SearchRequest\032\031.eventlogs.String" +
      "Response\"\000\022=\n\005alert\022\027.eventlogs.AlertReq" +
      "uest\032\031.eventlogs.StringResponse\"\000B,\n\022ser" +
      "vices.eventlogsB\024EventlogsServiceImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eventlogs_StatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eventlogs_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventlogs_StatusRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_eventlogs_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eventlogs_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventlogs_SearchRequest_descriptor,
        new java.lang.String[] { "Request", "Parameter", });
    internal_static_eventlogs_AlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_eventlogs_AlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventlogs_AlertRequest_descriptor,
        new java.lang.String[] { "Request", "Email", "Message", });
    internal_static_eventlogs_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_eventlogs_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventlogs_StringResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
