// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventlogs.proto

package services.eventlogs;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventlogs.SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();

  /**
   * <code>string parameter = 2;</code>
   */
  java.lang.String getParameter();
  /**
   * <code>string parameter = 2;</code>
   */
  com.google.protobuf.ByteString
      getParameterBytes();
}
