// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventlogs.proto

package services.eventlogs;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventlogs.StatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
