// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventlogs.proto

package services.eventlogs;

public interface StringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventlogs.StringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
